window.SALES_BATTLECARDS = [
  {
    "q_number": 1,
    "question": "The changes below are only required on the migrated dashboard.",
    "context": "Section: The changes below are only required on the migrated dashboard. from test.pdf",
    "pitch": "The existing dashboard in Wave Growth Agency must remain as is.\nPlease do not use any snapshots from the existing agency account due to\nan ongoing company dispute.\nIn the new agency account PATIENTACQ, please use the Master Snapshot\nsetup.\n1. Change FIRST → MAP\nReplace the existing FIRST framework throughout the dashboard with MAP.\nMAP should be displayed in full as:\n Motivation:\n Assessment:\n Payment:\nNo logic changes. Remove the existing Financial, Intent, Readiness, Suitability and Trust\ndashboard metrics. The relevant fields are already created. We must be using the cumulative\nfields. (cv)\nCustom values for colours:\nI have added in the custom values required but these will be connected to the new dashboard.\n2. MAP drill-down\nEach MAP, when clicked, should work in the same way as the other clickable dashboard/patient\ndata.\nWhen clicking Motivation, Assessment or Payment, show the individual contacts/opportunities\nincluded in that score and their respective score.\n3. Lost Reasons\nThe current Lost Reasons section is limited to reasons associated with FIRST.\nChange this so that Lost Reasons displays the distribution of all Lost Reason values,\nregardless of what the reason is.\nFor example, if the CRM contains:\n Finances\n No response\n Timing\n Chose competitor\n Other\nall should be shown automatically rather than requiring the dashboard to recognise a predefined\nFIRST category. Remove any FIRST filtering.\n4. Unassigned Lost Patients\nAdd visibility of lost patients who do not have a Lost Reason assigned.\nAny leads in any of the listed pipeline stages without a lost reason should show as\nunassigned: No contact, Lost, No show, Attended\nDisplay them as something like: Unassigned: 10\nIt would be great if we make this clickable to view dashboard/patient data, like the other\nclickable elements to view all unassigned patients.\n5. Opportunity → Contact\nMake the Opportunity Name clickable wherever individual opportunities are displayed.\nClicking the opportunity name should take the user directly to that patient’s contact record in\nGHL.\nIf we can implement this, can we please make sure there’s a back button to click back to the\ndashboard to the relevant view where they clicked the initial patient name.\n6. Dashboard Font & Emojis\nChange the dashboard display font to Tanker.\nhttps://www.fontshare.com/?q=Tanker\nPlease remove all emojis.\n7. Dashboard Date Picker\nThe dashboard currently has its own date picker.\nIf possible, remove this and have the dashboard use/tap into the existing date picker already\navailable on the main dashboard, so both use the same selected date range.\nThis is a minor improvement and not a priority if it isn’t straightforward to implement.\n8. Key\nNext to “Total scored: 0”, can we please add a key for the client.\nTotal scored: 0 |  Established   Partial 🔴 Missed",
    "source": "test.pdf"
  }
];
